"""Init

Revision ID: 73f721630312
Revises: 
Create Date: 2025-09-30 15:26:30.291193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73f721630312'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', name='taxistatus'), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('callback_url', sa.String(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('x BETWEEN 1 AND 100', name='ck_taxis_x_range'),
    sa.CheckConstraint('y BETWEEN 1 AND 100', name='ck_taxis_y_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_taxis_id'), 'taxis', ['id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taxi_id', sa.Integer(), nullable=True),
    sa.Column('start_x', sa.Integer(), nullable=False),
    sa.Column('start_y', sa.Integer(), nullable=False),
    sa.Column('end_x', sa.Integer(), nullable=False),
    sa.Column('end_y', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='tripstatus'), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('pickup_time', sa.DateTime(), nullable=True),
    sa.Column('dropoff_time', sa.DateTime(), nullable=True),
    sa.Column('waiting_time_min', sa.Integer(), nullable=True),
    sa.Column('travel_time_min', sa.Integer(), nullable=True),
    sa.Column('total_distance', sa.Integer(), nullable=True),
    sa.Column('route_meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['taxi_id'], ['taxis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_taxis_id'), table_name='taxis')
    op.drop_table('taxis')
    # ### end Alembic commands ###
