[project]
name = "client-simulator"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.117.1",
    "uvicorn[standard]>=0.37.0",
    "httpx>=0.27",
    "pydantic-settings>=2.4",
    "common>=0.1.0"
]
